set_property PACKAGE_PIN F17 [get_ports {PWM_OUT_0[4]}]
set_property PACKAGE_PIN V16 [get_ports {PWM_OUT_0[3]}]
set_property PACKAGE_PIN Y11 [get_ports {PWM_OUT_0[0]}]
set_property PACKAGE_PIN T5 [get_ports {PWM_OUT_0[1]}]
set_property PACKAGE_PIN Y12 [get_ports {PWM_OUT_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM_OUT_0[0]}]



set_property PACKAGE_PIN M17 [get_ports {PWM_OUT_0[5]}]

set_property PACKAGE_PIN K18 [get_ports {MY_IN0_0[3]}]
set_property PACKAGE_PIN P16 [get_ports {MY_IN0_0[2]}]
set_property PACKAGE_PIN K19 [get_ports {MY_IN0_0[1]}]
set_property PACKAGE_PIN Y16 [get_ports {MY_IN0_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN0_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN0_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN0_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN0_0[0]}]
set_property PACKAGE_PIN G15 [get_ports {MY_IN1_0[3]}]
set_property PACKAGE_PIN P15 [get_ports {MY_IN1_0[2]}]
set_property PACKAGE_PIN W13 [get_ports {MY_IN1_0[1]}]
set_property PACKAGE_PIN T16 [get_ports {MY_IN1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN1_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN1_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN1_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_IN1_0[0]}]
set_property PACKAGE_PIN M14 [get_ports {MY_OUT_0[3]}]
set_property PACKAGE_PIN M15 [get_ports {MY_OUT_0[2]}]
set_property PACKAGE_PIN G14 [get_ports {MY_OUT_0[1]}]
set_property PACKAGE_PIN D18 [get_ports {MY_OUT_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_OUT_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_OUT_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_OUT_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MY_OUT_0[0]}]
